name: clock_rhythm
description: A local-first focus rhythm and Todo app for Windows and Android.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  audioplayers: ^6.8.1
  characters: ^1.4.1
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  file_picker: ^12.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  go_router: ^17.5.0
  intl: 0.20.2
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  tray_manager: ^0.5.3
  window_manager: ^0.5.2

dev_dependencies:
  analyzer: 12.1.0
  build_runner: ^2.15.1
  drift_dev: ^2.34.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^3.18.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/CHIME14.mp3
    - assets/images/icon.png
    - windows/runner/resources/app_icon.ico
